### PR TITLE
Gradle Conversion

### PR DESCRIPTION
**Pull request by ghost**
My colleagues and I want to experiment with creating a Slack bot so that we could play IF games through Slack. Just an experiment with Slack.

We're used to using Gradle for building our projects, so we reconfigured our fork of Zax for Gradle. Those changes are in this pull request if you'd like to make use of them.

### CODE REVIEW

**Comment by mattkimmel** [comment]
Thank you for contributing this, and for bringing Zax a little closer to the 21st century! Thanks for cleaning up the code a bit, as well.

**Comment by ghost** [comment]
You're welcome!

Our thinking is that we won't have to make significant changes to Zax itself. Our thinking was that the ZUserInterface will make integration part relatively simple. The actual implementation might get interesting. :)

If we do modify our fork of Zax would you prefer we preserve the "dependency free" state of the project? And do you have a preference of a Java version to conform to?

**Comment by mattkimmel** [comment]
Hey @iain-davis! Embarrassingly enough, I never saw this comment when you left it, and just happened to notice it while I was reviewing this repo. I see that you've made lots of progress on the Slack bot since then, which is great! I apologize if I held you up at all.

My answer to this would have been "do whatever makes sense", and I'm glad you did.

Would you mind if I backported your excellent work on Zax back to this repo?

Thanks, and sorry again about the ridiculously long delay.

**Comment by ghost** [comment]
Feel free to merge in to your fork any of the changes you wish. 

Sort of an amusing coincidence -- we had gotten busy and so our side project stalled, until a few days ago when I started taking a look at it again. :)

**Comment by mattkimmel** [comment]
Thanks, Iain! And thanks for making the code so much better. Glad you're having time to look at this again!

**Pull request merged**
